-- Drinkit! Supabase Schema

-- 1. Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  total_price DECIMAL NOT NULL,
  status TEXT DEFAULT 'Preparing' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Order Items Table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  product_name TEXT NOT NULL,
  size TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price DECIMAL NOT NULL
);

-- 4. Sample Data
INSERT INTO products (name, description, price, image_url) VALUES
('Midnight Espresso', 'Intense, dark, and mysteriously smooth.', 5.00, 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800'),
('Velvet Cappuccino', 'Creamy foam atop a rich espresso base.', 8.00, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'),
('Caramel Macchiato', 'Sweet caramel swirls with steamed milk.', 12.00, 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800'),
('Oat Milk Latte', 'Plant-based goodness with a nutty finish.', 10.00, 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=800');

-- 5. RLS Policies
-- Products: Everyone can read
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON products FOR SELECT USING (true);

-- Orders: Users can read and write their own
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert their own orders" ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view their own orders" ON orders FOR SELECT USING (auth.uid() = user_id);

-- Order Items: Users can read and write based on their order_id
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert order items" ON order_items FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_id AND orders.user_id = auth.uid())
);
CREATE POLICY "Users can view order items" ON order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_id AND orders.user_id = auth.uid())
);
